src/pe64/imports.rs
src/pe64/pe.rs
src/pe64/tls.rs
src/util/mod.rs
src/util/slice_len.rs

Introduce the trait `SliceLen` implemented for
* `usize` to indicate an array with known length
* `FnMut(&T) -> bool` to scan for the sentinel value
Further development probably requires some form of specialization.

Overload the slice reading functions

---

Cargo.toml
src/bin/ms-rtti.rs
src/pe64/debug.rs
src/pe64/exports.rs
src/pe64/file.rs
src/pe64/imports.rs
src/pe64/pe.rs
src/pe64/scanner.rs
src/pe64/tls.rs
src/pe64/view.rs

New PE reading functions:
* `Pe::slice(rva, min_size, align)`
Same as the old `slice_rva` function.
* `Pe::slice_bytes(rva)`
Helper which calls `slice(rva, 0, 1)` convenience method.
* `Pe::read(va, min_size, align)`
Same as the old `slice_rva` but now accepts a `Va` instead.
This is avoids inlined `va_to_rva` and can now distinguish null `Va` from image base `Va`.
* `Pe::read_bytes(va)`
Helper which calls `read(va, 0, 1)` convenience method.
Enforce alignment again in the functions returning a reference, can be turned off with the `unsafe_alignment` feature.
* `Pe::derva_copy` and `Pe::deref_copy` returning a copy of `T` which works with unaligned addresses.
* Renamed to `Pe::derva_str` and `Pe::deref_str` for overloading them in the future for other string types.
Includes refactoring …

Refactor PE Reading

---

src/image.rs
src/pe64/base_relocs.rs
src/resources/mod.rs

* Remove all `#[repr(packed)]` on the IMAGE structs due to a misunderstanding of the Windows.h struct definitions: Only the old 16-bit headers want 2 byte packing, all the others want 4 byte packing. However all of these structs end up already aligned anyway. Safeguard their implementation by asserting their sizes.
Fixes rust-lang/rust#46043
* Explicitly specify the raw pointer type when casting from reference and calling a method on it.
Fixes rust-lang/rust#46906

Fix for new rustc warnings

---

src/pattern.rs
src/pe64/pe.rs
src/pe64/scanner.rs
src/pe64/view.rs

This branch contains three subjects:
* Add pattern atoms
- `Fuzzy(mask)` atom lets you match after applying a byte mask.
- `Many(limit)` atom skips bytes until the remainder of the pattern is found (like `.*` regex) or the limit is exceeded.
- `Pir(index)` atom to follow position independent references.
* Optimize sections for `PeView`, needs specialization to be completed.
* Attempt to expose the match result directly through a `&mut [Rva]`.
General refactoring to support the above features.
I was considering to split them in different PRs buuuuut...

Advanced patterns

---

src/pe64/resources.rs
src/resources/find.rs
src/resources/mod.rs

* Change example to remove unnecessary Option.
* Rename invalid utf8 path error enum name.
* Rename find_ to find_internal.
* Minor changes to documentation.

Minor internal resources refactor

---

src/pe32/image.rs
src/pe64/file.rs
src/pe64/image.rs
src/pe64/pe.rs
src/pe64/view.rs
tests/demo64.rs

Slice to one byte past the end of a section with length of zero should be allowed.

Fix off-by-one in PeFile and drop FileOffset type

---

src/pe32/mod.rs
src/pe64/file.rs
src/pe64/mod.rs
src/pe64/pe.rs
src/pe64/scanner.rs
src/pe64/view.rs

Add a method to `Pe` to query if it uses file or section alignment.
This lets the scanner avoid having to add custom logic to `Pe` so it can optimize its logic based on which alignment is used.
I'm sure it'll be useful elsewhere too.

Query alignment

---

examples/imphash.rs

Requested by #39
I'm unhappy how I'm straight up copy&pasting the function to work with both pe32 and pe32+ binaries. I know this is by design but maybe macros can help out here.
I'm also unhappy about the error handling, it should be easier to dispatch and handle errors between pe32 and pe32+ cases.

Implement imphash

---

src/bin/module-def.rs
src/pe64/exports.rs

The iter_names iterator returns its items in an odd (export, name) tuple when it more naturally maps to a key => value format with (name, export).

Swap exports iter_names Item tuple

---

src/bin/msrtti.rs
src/pe64/base_relocs.rs
tests/demo64.rs

I was very unhappy with the API, the only way to get something done required knowing the internal details of the base relocations.
So here's the new API:
`BaseRelocs::into_iter` gets you an iterator returning all the `Rva`s of relocations, skipping absolute relocs without giving relocation type information. Super simple and works as expected.
`BaseRelocs::iter_blocks` gets you an iterator over the relocation blocks. Advanced.
That seems nice.

Revamp base relocations

---

src/pe64/exports.rs
src/util/c_str.rs

This came up when writing tests, this API allows to check if the name table is valid and provides a linear scan lookup by name which doesn't fail on corrupted name table entries.

Exports query non sorted name table

---

Cargo.toml
src/lib.rs
src/resources/mod.rs

Optional dependency on data-encoding, encodes resources data bytes as base64 strings if the feature is enabled and the serializer is human readable.

Encode resources with data-encoding

---

src/pattern.rs
src/pe64/scanner.rs

Improve parser feedback, now has nicer error message and shows the position in the pattern where the syntax is faulty.
Add tests for the skip many feature, improve documentation of the skip many feature and trim what the parser accepts as valid, this is open for extension as needed.
Some refactoring of the parser code, it's still ugly however...

Support YARA hex strings Part2

---

src/util/align.rs
src/util/mod.rs

Useful for embedding binary files in the executable image with specific alignment, otherwise `include_bytes!` only has alignment of 1.

Align wrapper utils

---

examples/extract-icons.rs
src/resources/art.rs
src/resources/find.rs
src/resources/mod.rs
src/util/mod.rs
tests/demo64.rs

This PR is fairly heavy on breaking changes...
* Name now has an extra entry for Rust strings.
* When referring to resource names with Rust strings now expecting `#` prefix to match resource ids.
* Now consistently prints `#` prefix for resource ids.
* 'Deprecating' `WideStr` by straight up removing it.
Closes #191

Refactor Resource Naming

---

src/pe64/pe.rs

Some applications seem to lie about their resources directory size, promising a bigger size than there exists space in the executable! Yet windows seems to not care about this too much.
In practice this means the checks should happen later, while the resources are being parsed.
Fixes #198

Relax OOB check for Resources Directory

---

src/bin/findsig.rs

* Determine the number of save slots correctly.
* Always print hex literal prefix.

Improve findsig utility

---

Cargo.toml
changelog.md
examples/apisetschema/win10.rs
src/error.rs
src/mmap/windows.rs
src/proc-macros/lib.rs
src/proc-macros/pattern.rs
src/resources/find.rs

* Stop using deprecated `Error::description`
* Exclude tests/pocs/blob due to antivirus false positive
* Patterns accept newlines and tabs as whitespace

Small update

---

src/proc-macros/pattern.rs

The Skip atom with an argument of zero means to skip a number of bytes equal to the width of a pointer on the target platform.
The parser for the square brackets incorrectly generated a Skip atom with argument zero if the lower bound was zero.

Fix case of incorrect parsing of square brackets

---

Cargo.toml
src/base_relocs.rs
src/error.rs
src/lib.rs
src/pe64/file.rs
src/pe64/view.rs
src/proc-macros/pattern.rs
src/resources/find.rs
src/resources/group.rs
src/resources/mod.rs
src/resources/version_info.rs
src/util/mod.rs
src/util/wide_str.rs

Limit file operations and `mmap` feature to environments with standard library. Otherwise, do not depend on it. This also requires limiting `std::error::Error` implementation in error types only in std environments. Other than that, we are pulling Google's hashbrown, since `alloc::collections` does not include HashMap.

Add no_std support

---

src/pe64/file.rs
src/pe64/pe.rs
src/pe64/view.rs

Fixes #266.
Adds a method `image_base(&self) -> Va` to the `Pe` trait:
- For a `PeFile`, returns the preferred virtual address, i.e. `self.optional_header().ImageBase`.
- For a `PeView`, it returns the true virtual address of the image. By default, this is the same as the above, except when constructing via `PeView::module` (uses `base` directly) or via `from_bytes_and_base` (where it is provided by the user).
The return value of this method is used for VA/RVA conversions in the `Pe` trait, replacing `self.optional_header().ImageBase`.

Use correct base address for 32-bit ASLR images

---

src/pe32/msvc.rs
src/proc-macros/lib.rs

Currently, the following use of `pattern!` does not compile:
```rust
use pelite::pattern;
use pelite::pattern::Atom;
macro_rules! forward_pat {
($pat:literal) => {
pattern!($pat)
}
}
const PAT: &[Atom] = forward_pat("");
```
This is because `macro_rules!` capture expressions, like `$pat`, get wrapped in a `TokenTree::Group` with no delimiter to preserve the order of operations (see https://doc.rust-lang.org/beta/proc_macro/enum.Delimiter.html#variant.None).
This PR fixes this without adding dependencies on other parsing libraries by first checking if the input is a no-delimiter group, and if so, expanding before trying to match on a `TokenTree::Literal`.

Fix pattern proc macro not working in macro_rules
