src/lib.rs, src/pattern.rs, src/pe32/mod.rs, src/pe64/mod.rs, src/pe64/pe.rs, src/pe64/scanner.rs, tests/demo64.rs
What is required to merge this PR?
=> Pattern Scanning for PE binaries

Cargo.toml, examples/markovbin.rs
=> Example generating random looking x86-64 based on markov chains

src/bin/findsig.rs
Before deleting the old scanner crate, I found that I forgot about this nifty utility. After a rewrite it's as good as new!
=> Old findsig utility

demo/readme.md, src/bin/module-def.rs
=> Rename pemoddef to module-def

src/pe64/exports.rs, tests/demo64.rs
Add a way to conveniently query exports with a familiar API.
=> GetProcAddress

appveyor.yml
Reduce the number of CI builds and update to VS 2017.
=> Update Appveyor Script

examples/csgo/classes.rs, examples/csgo/cvars.rs, examples/csgo/datamaps.rs, examples/csgo/interfaces.rs, examples/csgo/recvtables.rs, examples/csgo/weapondata.rs, examples/tf2/classes.rs, examples/tf2/cvars.rs, examples/tf2/interfaces.rs, src/bin/msrtti.rs, src/pe64/debug.rs, src/pe64/exports.rs, src/pe64/file.rs, src/pe64/imports.rs, src/pe64/pe.rs, src/pe64/view.rs, src/util/c_str.rs, src/util/mod.rs, src/util/wide_str.rs
Rename the old string reading to c_str.
=> Introduce generic string reading

src/pattern.rs, src/pe64/scanner.rs
* Check compares the cursor against the save slot value and fails if not equal.
* Zero writes zero to the given save slot, useful in a case branch.
=> New pattern atoms

examples/csgo/classes.rs, examples/csgo/cvars.rs, examples/csgo/datamaps.rs, examples/csgo/interfaces.rs, examples/csgo/kbutton.rs, examples/csgo/stdout.md, src/bin/findsig.rs, src/image.rs, src/pe64/headers.rs, src/pe64/scanner.rs, src/wrap/headers.rs, src/wrap/scanner.rs, tests/demo64.rs
Finally cleaned up `Matches::next code`...
=> Scanner Refactor

Cargo.toml, src/lib.rs
And put `Pir` pointer type behind the unstable feature flag.
=> Feature flag for unstable features

examples/extract-icons.rs, src/resources/find.rs, src/resources/group.rs, src/resources/mod.rs
=> Parse Icons and Cursors

src/resources/version_info.rs
=> Add version info language string parser

src/resources/version_info.rs
Here's the change I mentioned preferring in my last comment in #134.
`VersionInfo::translation() -> Option<&[Language]>` becomes `VersionInfo::translations() -> &[Language]`, where the None becomes an empty slice. I think the ergonomics improvement is worth the semantic conflation of finding an empty VarFileInfo block and finding no VarFileInfo block.
=> Replace VersionInfo::translation() -> Option<&[Language]>

examples/apex/misc.rs, examples/apex/stdout.md
Includes signonstate and levelname
=> Apex Legends Shadowfall Update

src/util/align.rs
Functionality has been moved into a separate crate.
=> Remove Align structs

Cargo.toml, changelog.md, src/proc-macros/Cargo.toml, wasm/Cargo.toml
=> Release v0.9.0

src/resources/version_info.rs
Where the size of the version info is not aligned to a 32-bit boundary.
=> Fix parsing of version info

src/image.rs
=> Fix unwind code structure

Cargo.toml, src/image.rs
=> Fix definition of IMAGE_DYNAMIC_RELOCATION64

Cargo.toml, src/pe64/headers.rs, src/pe64/pe.rs, src/resources/group.rs, src/wrap/debug.rs, tests/tiny.rs, wasm/Cargo.toml
This is a _hard_ breaking change.
=> Upgrade to dataview 1.0
